-- Script d'initialisation de la base de données Supabase
-- Alignement avec la configuration de production (8 Jan 2026)

-- 1. Table Profiles (liée aux utilisateurs connectés)
create table public.profiles (
  id uuid not null,
  email text null,
  username text null,
  preferred_transport_mode text null default 'bike'::text,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- Activation Row Level Security (RLS) pour profiles
alter table public.profiles enable row level security;

-- Politiques de sécurité (Policies) pour profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

create policy "Users can select their own profile." on public.profiles
  for select using (auth.uid() = id);

-- 2. Table Favorite Spots (Lieux favoris et parkings associés)
create table public.favorite_spots (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  sport_facility_id text not null,
  sport_facility_name text not null,
  sport_facility_lat double precision not null,
  sport_facility_lng double precision not null,
  preferred_parking_id text null,
  preferred_parking_name text null,
  preferred_parking_type text null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint favorite_spots_pkey primary key (id),
  constraint favorite_spots_user_id_fkey foreign key (user_id) references profiles (id) on delete CASCADE,
  constraint favorite_spots_preferred_parking_type_check check (
    preferred_parking_type = any (array['car'::text, 'bike'::text])
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists idx_favorite_spots_unique_content on public.favorite_spots using btree (
  user_id,
  sport_facility_id,
  COALESCE(preferred_parking_id, 'NONE'::text)
) TABLESPACE pg_default;

-- Activation RLS pour favorite_spots
alter table public.favorite_spots enable row level security;

-- Politiques de sécurité pour favorite_spots
create policy "Users can view their own favorites" on public.favorite_spots
  for select using (auth.uid() = user_id);

create policy "Users can insert their own favorites" on public.favorite_spots
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own favorites" on public.favorite_spots
  for delete using (auth.uid() = user_id);

create policy "Users can manage their own favorites." on public.favorite_spots
  for all using (auth.uid() = user_id);

-- Trigger pour créer automatiquement un profil à l'inscription (Recommandé)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
